### ISSUE TITLE
Impossible to convert this PDF

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [matthiaskramm/swftools#151]
If anyone has the right pdf2swf command line to convert this PDF I will congratulate her/him!
various issues:
- id table overflow,
- glyph missing
[reosoulotat.pdf](https://github.com/matthiaskramm/swftools/files/5120072/reosoulotat.pdf)

**Comment by ousia** [comment]
I get the following segfault message:

```
Program received signal SIGSEGV, Segmentation fault.
FoFiTrueType::computeTableChecksum(unsigned char*, int) [clone .constprop.0] (data=0x800053f3a45f <error: Cannot access memory at address 0x800053f3a45f>, 
    length=1594834165, this=<optimized out>) at ../lib/pdf/xpdf/FoFiTrueType.cc:1776
1776	    word = ((data[i  ] & 0xff) << 24) +
```

And here is the backtrace:

``` bt
#0  FoFiTrueType::computeTableChecksum(unsigned char*, int) [clone .constprop.0] (data=0x800053f3a45f <error: Cannot access memory at address 0x800053f3a45f>, 
    length=1594834165, this=<optimized out>) at ../lib/pdf/xpdf/FoFiTrueType.cc:1776
#1  0x000055555565e701 in FoFiTrueType::writeTTF (outputFunc=<optimized out>, name=0x0, codeToGID=0x0, outputStream=0x555555a86580, this=0x555555a6db10)
    at ../lib/pdf/xpdf/FoFiTrueType.cc:1146
#2  FoFiTrueType::writeTTF (outputFunc=<optimized out>, name=0x0, codeToGID=0x0, outputStream=0x555555a86580, this=0x555555a6db10)
    at ../lib/pdf/xpdf/FoFiTrueType.cc:760
#3  SplashFTFontEngine::loadTrueTypeFont (codeToGIDLen=0, codeToGID=0x0, deleteFile=1, fileName=0x555555a73b40 "/tmp/4aa1e2fb50a0a532", idA=0x555555a45140, 
    this=0x5555558806a0) at ../lib/pdf/xpdf/SplashFTFontEngine.cc:160
#4  SplashFontEngine::loadTrueTypeFont(SplashFontFileID*, char*, int, unsigned short*, int) [clone .isra.0] (idA=0x555555a45140, 
    fileName=0x555555a73b40 "/tmp/4aa1e2fb50a0a532", deleteFile=1, codeToGID=0x0, codeToGIDLen=0, this=<optimized out>) at ../lib/pdf/xpdf/SplashFontEngine.cc:255
#5  0x000055555561ecf8 in SplashOutputDev::doUpdateFont (this=<optimized out>, state=<optimized out>) at ../lib/pdf/xpdf/SplashOutputDev.cc:1208
#6  0x0000555555614f3a in InfoOutputDev::updateFont (this=0x55555587f770, state=0x555555895c90) at ../lib/pdf/InfoOutputDev.cc:577
#7  0x00005555555e2132 in Gfx::opShowText (this=0x5555558823a0, args=0x7fffffffcc80, numArgs=<optimized out>) at ../lib/pdf/xpdf/Gfx.cc:3038
#8  0x00005555555df498 in Gfx::execOp (cmd=0x7fffffffcc70, numArgs=<optimized out>, args=0x7fffffffcc80, this=0x5555558823a0) at ../lib/pdf/xpdf/Gfx.cc:693
#9  Gfx::go (this=<optimized out>, topLevel=1) at ../lib/pdf/xpdf/Gfx.cc:584
#10 0x00005555555d6ba1 in Gfx::display (this=0x5555558823a0, obj=<optimized out>, topLevel=1) at ../lib/pdf/xpdf/Gfx.cc:556
#11 0x0000555555656c52 in Page::displaySlice (rotate=<optimized out>, useMediaBox=1, crop=1, sliceX=-1, sliceY=-1, sliceW=-1, sliceH=-1, abortCheckCbk=0x0, 
    abortCheckCbkData=0x0, catalog=0x5555557eafd0, printing=<optimized out>, vDPI=72, hDPI=<optimized out>, out=<optimized out>, this=0x5555557ef200)
    at ../lib/pdf/xpdf/Page.cc:317
#12 Page::display (rotate=0, useMediaBox=1, crop=1, abortCheckCbk=0x0, abortCheckCbkData=0x0, catalog=0x5555557eafd0, printing=<optimized out>, vDPI=72, 
    hDPI=<optimized out>, out=<optimized out>, this=0x5555557ef200) at ../lib/pdf/xpdf/Page.cc:264
#13 PDFDoc::displayPage(OutputDev*, int, double, double, int, int, int, int, int (*)(void*), void*) [clone .constprop.0] (this=<optimized out>, out=0x55555587f770, 
    page=page@entry=2, hDPI=72, vDPI=72, printing=0, abortCheckCbkData=<optimized out>, abortCheckCbk=<optimized out>, crop=<optimized out>, 
    useMediaBox=<optimized out>, rotate=<optimized out>) at ../lib/pdf/xpdf/PDFDoc.cc:317
#14 0x00005555555b40fc in pdf_open (src=<optimized out>, filename=<optimized out>) at ../lib/pdf/pdf.cc:542
#15 0x0000555555593183 in main (argn=2, argv=0x7fffffffd938) at /usr/src/debug/swftools-0.9.2-19.fc37.x86_64/src/pdf2swf.c:736
```
